import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import api, { formatApiError } from "../lib/api";
import { ArrowUpRight, CircleDollarSign, MessageCircle, Users, WalletCards } from "../icons";

const formatRupees = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;

export default function DashboardPage() {
  const [summary, setSummary] = useState(null); const [payments, setPayments] = useState([]); const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([api.get("/api/v1/admin/dashboard/summary"), api.get("/api/v1/admin/payments", { params: { status: "overdue" } })]).then(([summaryResponse, paymentsResponse]) => { setSummary(summaryResponse.data); setPayments(paymentsResponse.data.slice(0, 4)); }).catch((error) => setNotice(formatApiError(error))); }, []);
  const cards = summary ? [["Collected this month", formatRupees(summary.total_collected), CircleDollarSign, "sage"], ["Total pending", formatRupees(summary.total_pending), WalletCards, "amber"], ["Overdue accounts", summary.overdue_count, ArrowUpRight, "coral"], ["Reminders today", summary.reminders_today, MessageCircle, "ink"]] : [];
  return <section data-testid="dashboard-page"><PageHeader eyebrow="Monday, 24 June" title="A clear view of your studio." description="Here’s what needs your attention today." action={<Link to="/clients" className="primary-button" data-testid="dashboard-add-client-link"><Users size={17} />Add client</Link>} />{notice && <p className="inline-notice" data-testid="dashboard-notice">{notice}</p>}<div className="metric-grid">{cards.map(([label, value, Icon, tone]) => <article className={`metric-card ${tone}`} key={label} data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div><p>{label}</p><strong>{value}</strong></div><span><Icon size={21} /></span></article>)}</div><div className="dashboard-grid"><section className="overview-panel" data-testid="payment-attention-panel"><div className="panel-heading"><div><p className="eyebrow">Payment attention</p><h2>Overdue payments</h2></div><Link to="/finances" data-testid="view-all-finances-link">View all <ArrowUpRight size={16} /></Link></div><div className="mini-table">{payments.map((payment) => <div className="mini-row" key={payment.id} data-testid={`overdue-payment-${payment.id}`}><div className="person-dot">{payment.client?.full_name?.[0]}</div><div><strong>{payment.client?.full_name}</strong><small>Due {payment.due_date} · {payment.days_overdue} days late</small></div><b>{formatRupees(payment.amount_due - payment.amount_paid)}</b><span className="status-chip overdue">Overdue</span></div>)}{!payments.length && <p className="empty-copy" data-testid="no-overdue-payments">Nothing overdue right now.</p>}</div></section><aside className="studio-note" data-testid="studio-insight-panel"><p className="eyebrow">Studio pulse</p><h2>{summary?.active_clients || 0} active practitioners</h2><p>Your current projected monthly revenue is <strong>{formatRupees(summary?.projected_revenue)}</strong>.</p><Link to="/reminders" className="text-link" data-testid="open-reminders-link">Review reminder queue <ArrowUpRight size={16} /></Link></aside></div></section>;
}