import { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import api, { formatApiError } from "../lib/api";
import { Download, MessageCircle, Search } from "../icons";

export default function FinancesPage() {
  const [payments, setPayments] = useState([]); const [filter, setFilter] = useState("overdue"); const [notice, setNotice] = useState("");
  const load = async () => { try { setPayments((await api.get("/api/v1/admin/payments", { params: filter ? { status: filter } : {} })).data); } catch (error) { setNotice(formatApiError(error)); } };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [filter]);
  const queue = async (paymentId) => { try { const result = await api.post("/api/v1/admin/reminders/send-manual", { payment_ids: [paymentId] }); setNotice(result.data.results[0].status === "queued" ? "Reminder safely queued." : result.data.results[0].reason); } catch (error) { setNotice(formatApiError(error)); } };
  const exportLedger = async () => { const response = await api.get("/api/v1/admin/payments/export", { responseType: "blob" }); const url = window.URL.createObjectURL(new Blob([response.data])); const link = document.createElement("a"); link.href = url; link.download = "divine-yoga-ledger.csv"; link.click(); window.URL.revokeObjectURL(url); };
  return <section data-testid="finances-page"><PageHeader eyebrow="Finance tracker" title="Payments" description="A complete ledger for every fee, due date, and follow-up." action={<button className="secondary-button" data-testid="export-ledger-button" onClick={exportLedger}><Download size={17} />Export ledger</button>} /><div className="tab-bar" data-testid="payment-filter-tabs">{[["overdue", "Overdue"], ["pending", "Pending"], ["paid", "Paid"], ["", "All"]].map(([value, label]) => <button key={label} data-testid={`payment-filter-${label.toLowerCase()}`} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{label}</button>)}</div>{notice && <p className="inline-notice" data-testid="finance-notice">{notice}</p>}<div className="data-table-wrap"><table data-testid="payments-table"><thead><tr><th>Client</th><th>Due date</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} data-testid={`payment-row-${payment.id}`}><td><strong>{payment.client?.full_name}</strong><small>{payment.client?.phone_number}</small></td><td>{payment.due_date}<small>{payment.days_overdue ? `${payment.days_overdue} days overdue` : ""}</small></td><td>₹{(payment.amount_due - payment.amount_paid).toLocaleString("en-IN")}</td><td><span className={`status-chip ${payment.payment_status}`}>{payment.payment_status}</span></td><td><button className="table-action" data-testid={`send-reminder-${payment.id}`} onClick={() => queue(payment.id)} disabled={!payment.client?.whatsapp_opt_in} title={!payment.client?.whatsapp_opt_in ? "WhatsApp reminders are disabled for this client" : "Queue a WhatsApp reminder"}><MessageCircle size={16} />Remind</button></td></tr>)}{!payments.length && <tr><td colSpan="5" className="empty-cell" data-testid="payments-empty-state">No payments in this view.</td></tr>}</tbody></table></div></section>;
}