import { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import api, { formatApiError } from "../lib/api";
import { CheckCircle2, MessageCircle, Plus } from "../icons";

export default function RemindersPage() {
  const [templates, setTemplates] = useState([]); const [logs, setLogs] = useState([]); const [notice, setNotice] = useState("");
  const load = async () => { try { const [templateResponse, logResponse] = await Promise.all([api.get("/api/v1/admin/reminders/templates"), api.get("/api/v1/admin/reminders/logs")]); setTemplates(templateResponse.data); setLogs(logResponse.data); } catch (error) { setNotice(formatApiError(error)); } };
  useEffect(() => { load(); }, []);
  const addTemplate = async () => { const name = window.prompt("Template name"); const message = window.prompt("Reminder message. Use {name}, {amount}, {due_date}, {month}, {studio_name}."); if (!name || !message) return; try { await api.post("/api/v1/admin/reminders/templates", { name, trigger_type: "overdue", offset_days: 3, message_body: message, is_active: true }); setNotice("Template saved."); load(); } catch (error) { setNotice(formatApiError(error)); } };
  return <section data-testid="reminders-page"><PageHeader eyebrow="WhatsApp reminder engine" title="Reminders" description="Messages are safely queued and logged until your WATI connection is added." action={<button className="primary-button" data-testid="add-reminder-template-button" onClick={addTemplate}><Plus size={17} />New template</button>} />{notice && <p className="inline-notice" data-testid="reminder-notice">{notice}</p>}<div className="reminder-layout"><section><div className="section-heading"><MessageCircle size={19} /><h2>Active templates</h2></div><div className="template-stack">{templates.map((template) => <article className="template-card" key={template.id} data-testid={`template-card-${template.id}`}><div><span className="tag">{template.trigger_type.replaceAll("_", " ")}</span><h3>{template.name}</h3><p>{template.message_body}</p></div><small>{template.offset_days} day{template.offset_days === 1 ? "" : "s"} offset</small></article>)}</div></section><section className="queue-panel" data-testid="reminder-log-panel"><div className="section-heading"><CheckCircle2 size={19} /><h2>Queue & delivery log</h2></div>{logs.length ? logs.map((log) => <div className="queue-row" key={log.id} data-testid={`reminder-log-${log.id}`}><div className="person-dot">{log.client_name?.[0]}</div><div><strong>{log.client_name}</strong><small>{log.message_preview}</small></div><span className={`status-chip ${log.delivery_status}`}>{log.delivery_status}</span></div>) : <div className="empty-log" data-testid="reminder-logs-empty-state"><img src="https://images.pexels.com/photos/4464468/pexels-photo-4464468.jpeg" alt="Zen stones" /><p>No messages have been queued yet.</p></div>}</section></div></section>;
}